### ISSUE TITLE
Individual Project - Checkpoint 1

### ISSUE THREAD

**Issue by Mlor10** [Mlor10/indieProject#2]
@pawaitemadisoncollege - checkpoint 1 is ready for review

**Comment by pawaitemadisoncollege** [comment]
You've clearly put a lot of time and thought into your project already @Mlor10.

- [ ] Be sure that you have MVP stories to cover full crud. I think create and read are covered. Not 100% sure that update and delete are covered?
- [ ] I noticed you have a profile photo upload as part of the screens and stories. One simpler option, if you don't have time to write the full upload bit, would be to have the user provide a link to their photo, which you can then use to display the image.  This might also work for the card image? Any chance card images and data are available via a web service of some sort? 
- [ ] If you do opt for uploading the card images or profile photos, you *could* consider Amazon S3 for storage, and/or Amazon Rekognition for verifying the image is appropriate for your site. These would both be good independent learning topics and add to the complexity of your project.
- [ ] You have a great start with your project plan - I like that you thought down to the detail of the classes you will need. Consider adding tasks for regular deployment to AWS; this will include setting up a database on aws too (more about this in week 6).

Great work on this so far! Looking forward to seeing the first bits built out!
