### ISSUE TITLE
Individual Project - Checkpoint 2 ready for review

### ISSUE THREAD

**Issue by Mlor10** [Mlor10/indieProject#9]
@pawaitemadisoncollege - Checkpoint 2 is ready for review

**Comment by pawaitemadisoncollege** [comment]
Really great progress here @Mlor10! I am impressed that you have data coming back to the jsps already!

- [ ] It looks like you've converted over to the GenericDao; are you able to remove the UserDao (remember if you ever need to reference it, it'll still be available in GitHub).
- [ ] Do you have a diagram of your database; an ERD? It would help me provide better feedback if I am able to see the tables, columns and relationships. This can be generated right within IntelliJ: https://www.jetbrains.com/help/idea/creating-diagrams.html. If I overlooked this, please let me know!
- [ ] Great to see the one-to-many implemented here already! It would be a good idea to bulk up the delete scenario testing. If a user is deleted, what happens to their cards? What if a card is deleted, what, if anything should happen to the user? Write tests to verify what should happen, does happen. 
- [ ] You are doing a good job keeping up with your time log/journal. Be sure to also check off what's complete in the project plan, and move things forward in the timeline as needed.

**Comment by Mlor10** [comment]
Sorry for the late reply, I've added a db-diagram and here is the link
[db-diagram](https://github.com/Mlor10/indieProject/blob/master/DesignDocuments/db-diagram.png)
More things I've done
- removed UserDao

What I am planning to do next
- add a truncate feature/method for removing all of user A's cards if user A is removed
- Implement more of the db info into the jsp pages, like showing a list of the cards info in the home page
- create controller, entity, and crud for user threads and reports
- look into a way to set user profile images

**Comment by pawaitemadisoncollege** [comment]
Thanks for sharing the db diagram @Mlor10. 

Is a table to hold Threads still in the plan? (I'm assuming so, since you mentioned next steps includes crud for threads and reports).
